server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:file:./h2_database
    driver-class-name: org.h2.Driver
    username: s
    password: s
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
